-- CreateEnum
CREATE TYPE "TransactionCategory" AS ENUM ('SUBSCRIPTION', 'INVESTING', 'GROCERIES', 'SHOPPING', 'DINING', 'TRANSPORTATION', 'UTILITIES', 'ENTERTAINMENT', 'HOUSING', 'HEALTHCARE', 'EDUCATION', 'TRAVEL', 'OTHER');

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "category" "TransactionCategory" NOT NULL DEFAULT 'OTHER';
