import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Nunito_Sans } from 'next/font/google';

// Configure Nunito Sans with the weights you want to use
const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  // Include the weights you showed in the image: Regular (400), Medium (500), and Bold (700)
  weight: ['400', '500', '700'],
  variable: '--font-nunito-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
